general.import = [
  # uncomment the flavour you want below:
  # "~/.catppuccin/catppuccin-latte.toml"
  "~/.catppuccin/catppuccin-mocha.toml"
  # "~/.catppuccin/catppuccin-frappe.toml"
  # "~/.catppuccin/catppuccin-macchiato.toml"
]

[window]
startup_mode = "Fullscreen"
dynamic_padding = true
# resize_increments = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 18.25

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"
