return {
  { "goolord/alpha-nvim", enabled = false },
  { "dstein64/vim-startuptime", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  -- { "catppuccin/catppuccin", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "CopilotC-Nvim/CopilotChat.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "yetone/avante.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  -- { "keaising/im-select.nvim", enabled = false },
  -- { "folke/noice.nvim", enabled = false },
  -- { "nvim-lualine/lualine.nvim", enabled = false },
  -- { "letieu/btw.nvim", enabled = false },
}
